Add OBS source files for major distribution packages
clearcontainers/packaging pull request #1
Opened 2017-06-14 18:26 UTC by erick0z

This commit adds the necessary files to build clearcontainers
runtime, proxy, shim and the containers/virtcontainers pause
binary.

2017-06-14 19:00 UTC, devimc commented on proxy/README.md
> +This directory contains the sources to create rpm specfiles and debian source
s/specfiles/spec files/

2017-06-14 19:02 UTC, devimc commented on proxy/cc-proxy.dsc-template
> +Description:  An Open Containers Initiative (OCI) "proxy" that launches an Intel VT-x secured Clear Containers 2.1 hypervisor, rather than a standard Linux container.
s/Clear Containers 2.1/Clear Containers 3.0/

2017-06-14 19:04 UTC, devimc commented on proxy/debian.control-template
> + An Open Containers Initiative (OCI) "proxy" that launches an Intel VT-x secured Clear Containers 2.1 hypervisor, rather than a standard Linux container.
s/2.1/3.0/

2017-06-14 19:05 UTC, devimc commented on runtime/README.md
> +This directory contains the sources to create rpm specfiles and debian source
s/specfiles/spec files/

2017-06-14 19:06 UTC, devimc commented on runtime/cc-runtime.dsc-template
> +Description:  An Open Containers Initiative (OCI) "runtime" that launches an Intel VT-x secured Clear Containers 2.1 hypervisor, rather than a standard Linux container.
s/2.1/3.0/

2017-06-14 19:06 UTC, devimc commented on shim/README.md
> +This directory contains the sources to create rpm specfiles and debian source
s/specfiles/spec files/

2017-06-14 19:07 UTC, devimc commented on virtcontainers-pause/README.md
> +This directory contains the sources to create rpm specfiles and debian source
s/specfiles/spec files/

2017-06-14 19:09 UTC, devimc commented on shim/debian.control-template
> + An Open Containers Initiative (OCI) "runtime" that launches an Intel VT-x secured Clear Containers 2.1 hypervisor, rather than a standard Linux container.
s/2.1/3.0

2017-06-14 19:11 UTC, devimc commented on virtcontainers-pause/virtcontainers-pause.dsc-template
> +Description:  An Open Containers Initiative (OCI) "runtime" that launches an Intel VT-x secured Clear Containers 2.1 hypervisor, rather than a standard Linux container.
s/2.1/3.0

2017-06-14 19:25 UTC, devimc commented
lgtm

2017-06-14 19:28 UTC, devimc commented
because he uses the best editor in the world **emacs**

2017-06-14 20:06 UTC, gorozco1 requested changes
@erick0z reviewed, please change some minor tweaks

2017-06-14 20:06 UTC, gorozco1 commented on proxy/debian.control-template
> +Debtransform-Tar: cc-proxy-@VERSION@+git.@HASH_TAG@.tar.gz
should't this be @VERSION_DEB_TRANSFORM@ ?, also please add DEBTRANSFORM-RELEASE: 1

2017-06-14 20:06 UTC, gorozco1 commented on proxy/VERSION
> +3.0.0-alpha.0 8b2978d044f5efce201d5f2977fcc51b89e742c0
Please create a file in the root of the repository called versions.txt similar to 
https://github.com/01org/cc-oci-runtime/blob/master/versions.txt

Then all you have to do is

`source ../versions.txt `

2017-06-14 20:06 UTC, gorozco1 commented on proxy/update_proxy.sh
> +DEFAULT_VERSION=$(cat VERSION | awk '{print $1}')
```
source ../versions.txt
VERSION=${$1:-$cc-proxy}
```

2017-06-14 20:06 UTC, gorozco1 commented on shim/debian.control-template
> +Debtransform-Tar: cc-shim-@VERSION@+git.@HASH_TAG@.tar.gz
`@VERSION_DEB_TRANSFORM@`

2017-06-14 20:06 UTC, gorozco1 commented on shim/update_shim.sh
> +DEFAULT_VERSION=$(cat VERSION | awk '{print $1}')
```
source ../versions.txt
VERSION=${$1:-$cc-shim}
```

2017-06-14 20:06 UTC, gorozco1 commented on virtcontainers-pause/VERSION
> +0.7.0 93aa8226e6fa7e9bb2d553b571209f4f94e96348
remove this file add ../versions.txt

2017-06-14 20:06 UTC, gorozco1 commented on virtcontainers-pause/debian.control-template
> +Debtransform-Tar: virtcontainers-pause-@VERSION@+git.@HASH_TAG@.tar.gz
`@VERSION_DEB_TRANSFORM@`

2017-06-14 20:06 UTC, gorozco1 commented on virtcontainers-pause/update_pause.sh
> +DEFAULT_VERSION=$(cat VERSION | awk '{print $1}')
```
source ../versions.txt
VERSION=${$1:-$virtcontainers}
```

2017-06-14 20:06 UTC, gorozco1 commented on virtcontainers-pause/update_pause.sh
> +DEFAULT_VERSION=$(cat VERSION | awk '{print $1}')
rename `update_pause.sh` to `update_virtcontainers_pause.sh` for clarity

2017-06-14 20:06 UTC, gorozco1 commented on virtcontainers-pause/virtcontainers-pause.dsc-template
> +Debtransform-Tar: virtcontainers-pause-@VERSION@+git.@HASH_TAG@.tar.gz
for sanity add also @VERSION_DEB_TRANSFORM@ please

2017-06-14 21:24 UTC, rcaballeromx requested changes
Commented with the grammar and clarity fixes needed.

2017-06-14 21:24 UTC, rcaballeromx commented on proxy/README.md
> +This directory contains the sources to create rpm spec files and debian source
... and Debian\* source

2017-06-14 21:24 UTC, rcaballeromx commented on proxy/README.md
> +control files to create ``cc-proxy`` The proxy of Intel® Clear Containers.
control files to create the Intel® Clear Containers proxy: ``cc-proxy``.

2017-06-14 21:24 UTC, rcaballeromx commented on proxy/README.md
> +With these files we generated Fedora and Ubuntu packages for this component.
+To generate the Fedora\* and Ubuntu\* packages for this component enter:

2017-06-14 21:24 UTC, rcaballeromx commented on proxy/README.md
> +This script will update the sources to create ``cc-proxy`` packages.
This script updates the sources to create the following ``cc-proxy`` packages:

2017-06-14 21:24 UTC, rcaballeromx commented on runtime/README.md
> +# cc-runtime
See my comments on the proxy README. The same comments and changes are needed on this file.

2017-06-14 21:24 UTC, rcaballeromx commented on shim/README.md
> +# cc-shim
See my comments on the proxy README. The same comments and changes are needed on this file.

2017-06-14 21:24 UTC, rcaballeromx commented on virtcontainers-pause/README.md
> +# cc-runtime
See my comments on the proxy README. The same comments and changes are needed on this file.

2017-06-14 21:24 UTC, rcaballeromx commented on virtcontainers-pause/README.md
> +control files to create ``pause`` binary from github.com/containers/virtcontainers.
control files to create the ``pause`` binary from the github.com/containers/virtcontainers repository.

2017-06-14 21:56 UTC, erick0z commented
@devimc, @gorozco1, @rcaballeromx I've addressed the comments. Thanks for the feedback!

2017-06-16 14:19 UTC, rcaballeromx approved these changes
Excellent, thanks for making the changes.

2017-06-19 15:19 UTC, gorozco1 approved these changes

2017-06-19 15:19 UTC, gorozco1 commented on versions.txt
> +virtcontainers_pause_version=0.7.0
`virtcontainers_pause_version` should be `virtcontainers_version`, Because the version refers to the project not only `pause`

2017-06-19 15:19 UTC, gorozco1 commented on versions.txt
> +virtcontainers_pause_hash=93aa8226e6fa7e9bb2d553b571209f4f94e96348
`virtcontainers_pause_hash` to `virtcontainers_hash`

2017-06-19 15:19 UTC, merged