Update to 3.0.0-alpha-2
clearcontainers/packaging pull request #11
Opened 2017-06-29 21:23 UTC by erick0z

Update runtime, proxy and shim to 3.0.0-alpha.2
Allow custom APIURLs for local OBS instances.

Fixes https://github.com/clearcontainers/packaging/issues/9

2017-06-29 21:28 UTC, gorozco1 commented
@erick0z Please remove virtcontainers-pause and add https://github.com/clearcontainers/runtime/pull/276 as a patch to this PR.

2017-06-30 15:50 UTC, gorozco1 requested changes
Could you also add 
Fixes # in the commit message?

2017-06-30 19:33 UTC, gorozco1 requested changes
please remove virtcontainers related stuff from versions.txt

2017-06-30 19:33 UTC, gorozco1 commented on versions.txt
>  virtcontainers_version=0.7.0
remove virtcontainers_version

2017-06-30 19:33 UTC, gorozco1 commented on versions.txt
>  virtcontainers_hash=93aa8226e6fa7e9bb2d553b571209f4f94e96348
remove virtcontainers_hash

2017-07-03 22:20 UTC, gorozco1 requested changes
end of files

2017-07-03 22:20 UTC, gorozco1 commented on runtime/cc-runtime-bin.install
> +pause/pause /var/lib/clear-containers/runtime/bundles/pause_bundle/bin/
emacs detected... no end of file

2017-07-03 22:20 UTC, gorozco1 commented on runtime/cc-runtime-config.install
> +config/configuration.toml /etc/clear-containers/configuration.toml
emacs detected... no end of file

2017-07-03 22:20 UTC, gorozco1 commented on runtime/cc-runtime.dsc-template
> + This package contain the configuration file.
emacs detected... no end of file

2017-07-03 22:20 UTC, gorozco1 commented on runtime/debian.control-template
> + This package contain the configuration file.
emacs detected... no end of file

2017-07-03 22:20 UTC, gorozco1 commented on runtime/debian.series
> +build-Add-containers-virtcontainers-pause-binary.patch
emacs detected... no end of file

2017-07-03 22:20 UTC, erick0z commented on runtime/cc-runtime-bin.install
> +pause/pause /var/lib/clear-containers/runtime/bundles/pause_bundle/bin/
oops

2017-07-03 22:31 UTC, gorozco1 approved these changes

2017-07-03 22:31 UTC, merged