Add support for native hot plug
clearcontainers/packaging pull request #133
Opened 2017-10-03 16:00 UTC by devimc

fixes #132

Signed-off-by: Julio Montes <julio.montes@intel.com>

2017-10-03 21:02 UTC, gorozco1 approved these changes

2017-10-03 22:09 UTC, miguelinux approved these changes
lgtm

2017-10-04 17:08 UTC, gorozco1 requested changes
@devimc Could you add a short description of the change and do the same in the issue so we have in the history why this change was made please.

2017-10-04 20:57 UTC, devimc commented
@gorozco1  done

2017-10-04 22:36 UTC, gorozco1 approved these changes

2017-10-04 22:36 UTC, merged