image: update image to 18400
clearcontainers/packaging pull request #158
Opened 2017-10-16 21:35 UTC by erick0z

This image contains relevant changes:
 - https://github.com/clearcontainers/agent/pull/131

Fixes #157

Signed-off-by: Erick Cardona <erick.cardona.ruiz@intel.com>

2017-10-16 21:38 UTC, jcvenegas approved these changes

2017-10-16 23:28 UTC, gorozco1 approved these changes
lgtm

2017-10-17 08:03 UTC, jodh-intel requested changes

2017-10-17 08:03 UTC, jodh-intel commented on clear-containers-image/debian.changelog
> +version: 18280
All of this descriptive text needs to be indented as it is currently making this changelog file "invalid". See:

- https://www.debian.org/doc/debian-policy/#debian-changelog-debian-changelog

Note that you can check when the file is valid by doing:

```
$ sudo apt-get -y install dpkg-dev
$ dpkg-parsechangelog -l /path/to/your/changelog
```

If the `dpkg-parsechangelog` command outputs anything to `stderr`, the file is invalid (it seems that checking the exit code isn't reliable as the command attempts to recover and ignore bad input).

2017-10-17 22:33 UTC, erick0z commented
@jodh-intel Fixed

2017-10-18 07:10 UTC, jodh-intel commented on clear-containers-image/debian.changelog
> +  Changes in package iptables (from 1.6.1-20 to 1.6.1-21):
Nit: I'd personally indent a little more (something like the following for maximum clarity - this is also still valid):

```
 * version: 18280

   Changes in package iptables (from 1.6.1-20 to 1.6.1-21):

       George T Kramer - iptables: Autospec creation for version 1.6.1

   https://download.clearlinux.org/releases/18280/clear/RELEASENOTES

```

2017-10-18 07:10 UTC, jodh-intel approved these changes

2017-10-18 15:59 UTC, merged