packages: Refactor setup scripts
clearcontainers/packaging pull request #167
Opened 2017-10-20 20:33 UTC by erick0z

this series of commits refactor the setup script allowing new features,
needed for some use cases and adding a better user experience.

Fixes #163

2017-10-20 21:44 UTC, gorozco1 requested changes

2017-10-20 21:44 UTC, gorozco1 commented on runtime/update_runtime.sh
>      d=$(date +"%a, %d %b %Y %H:%M:%S %z")
Replace this please.

`d=$(date -R)`

2017-10-20 21:44 UTC, gorozco1 commented on runtime/update_runtime.sh
> +    [ "$SCRIPT_DIR" != "." ] && echo "The script must be called from its base dir." && exit 1 || :
why is this needed?

2017-10-20 21:44 UTC, gorozco1 commented on runtime/update_runtime.sh
> +    [ "$SCRIPT_DIR" != "." ] && echo "The script must be called from its base dir." && exit 1 || :
For clarity better to use: 

`[ "$SCRIPT_DIR" != "." ] && echo "The script must be called from its base dir." && exit 1 || true`

2017-10-20 21:44 UTC, gorozco1 commented on runtime/update_runtime.sh
> +    [ -f $OBS_WORKDIR/debian.series ] && rm $OBS_WORKDIR/debian.series || :
`[ -f $OBS_WORKDIR/debian.series ] && rm $OBS_WORKDIR/debian.series || true`

2017-10-20 21:44 UTC, gorozco1 commented on runtime/update_runtime.sh
> +    [ -f debian.series ] && cp debian.series $OBS_WORKDIR || :
`[ -f debian.series ] && cp debian.series $OBS_WORKDIR || true`

2017-10-20 21:44 UTC, gorozco1 commented on runtime/update_runtime.sh
> +    [ ! -e /packages ] && mkdir /packages || :
`|| true`

2017-10-20 21:44 UTC, gorozco1 commented on runtime/update_runtime.sh
> +    [ ! -e /logs ] && mkdir /logs || :
`|| true`

2017-10-20 21:44 UTC, gorozco1 commented on runtime/update_runtime.sh
> +    BUILD_ARGS=('--local-package' '--no-verify' '--noservice' '--trust-all-projects' '--keep-pkgs=/packages')
`--no-verify` ?

2017-10-20 21:44 UTC, gorozco1 commented on runtime/update_runtime.sh
> +    [ -n "$VERBOSE" ] && set -x || :
`|| true`

2017-10-20 21:44 UTC, gorozco1 commented on runtime/update_runtime.sh
> +    [ -n "$APIURL" ] && APIURL="-A ${APIURL}" || :
`|| true`

2017-10-20 21:44 UTC, gorozco1 commented on runtime/update_runtime.sh
> +OPTS=`getopt -o abclprwvCVh: --long api-url,branch,commit-id,local-build,push,obs-repository,workdir,verbose,clean,verify,help: -n 'test' -- "$@"`
change `code` for $(code)

2017-10-23 10:17 UTC, jodh-intel requested changes

2017-10-23 10:17 UTC, jodh-intel commented on proxy/update_proxy.sh
> +  This script is intended to create Clear Containers 3.0 packages for the OBS
I'd change this to "Clear Containers 3.x" to make it more future-proof.

2017-10-23 10:17 UTC, jodh-intel commented on proxy/update_proxy.sh
> +    -w	       --workdir	 Repository directory
Indentation.

2017-10-23 10:17 UTC, jodh-intel commented on proxy/update_proxy.sh
> +    Usage example
s/Usage example/Usage examples:/

2017-10-23 10:17 UTC, jodh-intel commented on proxy/update_proxy.sh
> +    [ "$SCRIPT_DIR" != "." ] && echo "The script must be called from its base dir." && exit 1 || :
It might be worth adding a `die` function so you can simplify this slightly:
```
die()
{
  msg="$*"
  echo >&2 "ERROR: $msg"
  exit 1
}

  :
  :

[ "$SCRIPT_DIR" != "." ] && die "The script must be called from its base dir" || :

```

2017-10-23 10:17 UTC, jodh-intel commented on proxy/update_proxy.sh
> +    for file in ${files[@]}
Nit: You might want a `local file` here as you have defined a local for `files`?

2017-10-23 10:17 UTC, jodh-intel commented on proxy/update_proxy.sh
> +    [ ! -e /packages ] && mkdir /packages || :
I'd consider creating variables for paths like `/packages` and `/logs` to make maintaining these scripts easier.

2017-10-23 10:17 UTC, jodh-intel commented on proxy/update_proxy.sh
> +                ${distro} x86_64 *.spec | tee /logs/proxy_${distro}_build.log
Again, it wouldn't hurt to define a variable for `x86_64` to avoid the repetition here.

2017-10-23 10:17 UTC, jodh-intel commented on proxy/update_proxy.sh
> +    [[ $? != 0 ]] && exit 1 || echo "Verify succeed."
The `verify` function exits on error, so this could be simplified to the following I think:

```
verify
echo "Verify succeeded."
```

2017-10-23 10:17 UTC, jodh-intel commented on runtime/update_runtime.sh
> +    -w	       --workdir	 Repository directory
Indentation oddity again.

2017-10-23 10:17 UTC, jodh-intel commented on proxy/update_proxy.sh
> +    source ../versions.txt
I'd perform the `source` at the top of the script to avoid having to call it from (various) functions.

2017-10-23 10:18 UTC, jodh-intel commented
This PR looks like it's going to be very useful. However, these `update_*.sh` scripts are almost identical. I suggest refactoring a little further so that the 3 scripts can be "stubs" and call functions in a `lib.sh` or something. The stubs could then:

- `source lib.sh`
- Parse their arguments
- Make calls like this:
  ```
  clean $runtime_files

  set_versions "$cc_shim_version" "$cc_shim_hash"
  
  checkout_repo "$OBS_PROXY_REPO" ...
  ```

2017-11-03 17:19 UTC, erick0z commented
@jodh-intel, As you suggested, I've split some functions into a new ``scripts/pkglib.sh``. The remaining bits in each setup script are just properties needed for each component (like project names and static files, etc). Can you review this PR?

2017-11-07 17:30 UTC, jodh-intel approved these changes

2017-11-07 19:28 UTC, gorozco1 approved these changes

2017-11-07 19:28 UTC, gorozco1 commented
@erick0z this commit has the "do not merge" label is still the case?

2017-11-07 20:06 UTC, merged