Update runtime and shim to 3.0.0-alpha.4
clearcontainers/packaging pull request #27
Opened 2017-07-20 20:23 UTC by erick0z

Update runtime and shim to 3.0.0-alpha.4

- Update runtime and shim to 3.0.0-alplha.4
- Move dependencies to the meta package.

Add runtime dependencies' versions
    
    This commit adds new entries in the versions.txt for indicating the
    versions of the OBS packages in the stable repository. These are
    added to the spec/dsc files in the "Requires" section and in order
    to support the upgrade path when upgrading the runtime.

2017-07-20 20:24 UTC, erick0z commented
@gorozco1 Can you review?

2017-07-20 20:38 UTC, gorozco1 requested changes

2017-07-20 20:38 UTC, gorozco1 commented on versions.txt
> +shim_obs_ubuntu_version=3.0.0alpha.2+git.9d1a3ee-1.1
shim is version alpha.4 

https://github.com/clearcontainers/shim/tree/3.0.0-alpha.4

2017-07-20 20:40 UTC, gorozco1 commented
@erick0z can you stash your changes in a single commit please? 
I notice that only one commit has the keyword Fixes issue..

2017-07-20 22:25 UTC, erick0z commented
@gorozco1 We don't have travis setup for this repository. There is an issue for this https://github.com/clearcontainers/packaging/issues/15

2017-07-20 22:27 UTC, erick0z commented
@gorozco1  Squash done.

2017-07-20 22:45 UTC, gorozco1 requested changes
please remove also an extra line of the commit:

Signed-off-by: Erick Cardona <erick.cardona.ruiz@intel.com>

2017-07-20 22:45 UTC, gorozco1 commented on proxy/debian.changelog
> +cc-proxy (3.0.0-alpha.3) stable; urgency=medium
There are a n extra entry not needed in proxy/changelog please remove

2017-07-20 22:46 UTC, gorozco1 commented
We need a +1 from @chavafg in order to merge this and release the packages.

2017-07-21 18:02 UTC, erick0z commented
@gorozco1 Regarding the issues with the OBS packages, I'll fix 'em as soon OBS is back online, having some difficulties with the authentication system.

2017-07-21 19:46 UTC, GabyCT commented
@gorozco1 and @erick0z, I tried to do an update with the latest OBS packages however it is not working properly

2017-07-21 21:46 UTC, GabyCT commented
lgtm, tested on Fedora and Ubuntu

2017-07-24 16:09 UTC, gorozco1 approved these changes

2017-07-24 19:03 UTC, gorozco1 commented
Waiting for changelog updates by @erick0z

2017-07-24 19:04 UTC, erick0z commented
@gorozco1 pushed

2017-07-24 19:32 UTC, merged

2017-07-24 19:34 UTC, gorozco1 commented
Repos updated with clearcontainers 3 alpha-4

http://download.opensuse.org/repositories/home:/clearcontainers:/clear-containers-3/