Update to 3.0.0-alpha.1
clearcontainers/packaging pull request #5
Opened 2017-06-21 21:13 UTC by erick0z

Update runtime, proxy and shim to 3.0.0-alpha.1

Fixes https://github.com/clearcontainers/packaging/issues/4
Fixes https://github.com/clearcontainers/packaging/issues/2

2017-06-21 21:19 UTC, gorozco1 requested changes
The real fix for #4 is to provide two binaries in a package cc-runtime 

Could you push a PR only including a fix for #2 and rework the fix for #4  ?

2017-06-21 21:19 UTC, gorozco1 commented on runtime/cc-runtime.spec-template
> +Requires: virtcontainers-pause
The intention here is to remove completely `virtcontainers-pause` package and instead `cc-runtime` package should provide `cc-runtime` binary and `pause` binary

2017-06-21 22:44 UTC, gorozco1 commented on runtime/debian.rules
> +	cd $(GOPATH)/src/github.com/clearcontainers/runtime/ && make install DESTDIR=`pwd`/debian/cc-runtime PREFIX=/usr SYSCONFDIR=/etc
Why this have to be in one line?

2017-06-21 22:57 UTC, erick0z commented on runtime/debian.rules
> +	cd $(GOPATH)/src/github.com/clearcontainers/runtime/ && make install DESTDIR=`pwd`/debian/cc-runtime PREFIX=/usr SYSCONFDIR=/etc
For some reason, during the ubuntu build, it does not work having it splitted in two lines. I guess is related to the makefile stuff

2017-06-21 22:59 UTC, erick0z commented on runtime/debian.rules
> +	cd $(GOPATH)/src/github.com/clearcontainers/runtime/ && make install DESTDIR=`pwd`/debian/cc-runtime PREFIX=/usr SYSCONFDIR=/etc
well, when the make is performed, it changes to another directory, but in order to perform the go build, it needs to be in the gopath.

2017-06-21 23:02 UTC, gorozco1 commented on runtime/debian.rules
> +	cd $(GOPATH)/src/github.com/clearcontainers/runtime/ && make install DESTDIR=`pwd`/debian/cc-runtime PREFIX=/usr SYSCONFDIR=/etc
yes Makefile needs to watch them as a single line
so 

```
cd $(GOPATH)/src/github.com/clearcontainers/runtime/ ; \
   make install DESTDIR=`pwd`/debian/cc-runtime PREFIX=/usr SYSCONFDIR=/etc ; \
```

2017-06-22 16:42 UTC, gorozco1 approved these changes

2017-06-22 16:54 UTC, merged