packages: update to 3.0.0-beta.1
clearcontainers/packaging pull request #59
Opened 2017-08-14 21:56 UTC by erick0z

Update packages (cc-proxy, cc-runtime) to 3.0.0-beta.1.

Fixes #58

2017-08-14 22:09 UTC, gorozco1 requested changes
We need to update the clear-containers-image these packages depends on..

2017-08-14 22:09 UTC, gorozco1 commented on versions.txt
>  image_obs_fedora_version=16670-31.1
I think we need to update also the image that these package depends on

2017-08-14 22:23 UTC, erick0z commented on versions.txt
>  image_obs_fedora_version=16670-31.1
right!

2017-08-14 22:33 UTC, gorozco1 approved these changes

2017-08-15 21:34 UTC, erick0z commented
@gorozco1 Can we merge this?

2017-08-15 21:37 UTC, merged