Improve kernel structure to be the main repo from CC
clearcontainers/packaging pull request #68
Opened 2017-08-18 20:45 UTC by miguelinux

To set packaging as main repo some improvements were made.

- Now, update_kernel.sh fetch kernel version from upstream
- Keeps a release track version
- Deleted files not needed files in repo
- Updates CC mailing list address

2017-08-22 16:50 UTC, gorozco1 requested changes
please clarify

2017-08-22 16:50 UTC, gorozco1 commented on kernel/update_kernel.sh
> -CC_VERSIONS_FILE="../versions.txt"
why ignoring ../versions.txt?

2017-08-22 16:50 UTC, gorozco1 commented on kernel/update_kernel.sh
> -VERSION=${1:-$clear_vm_kernel_version}
we need to be able to build "any" version of the kernel with parameter

2017-08-23 16:33 UTC, miguelinux commented on kernel/update_kernel.sh
> -CC_VERSIONS_FILE="../versions.txt"
The idea is that packaging/kernel will be the first place where the kernel will be updated and after build test and a PR to packaging  will be propagated to others repos

2017-08-23 16:34 UTC, miguelinux commented on kernel/update_kernel.sh
> -VERSION=${1:-$clear_vm_kernel_version}
Ok, I'll fix it

2017-08-23 17:53 UTC, miguelinux commented
@gorozco1 changes are integrated

2017-08-23 21:02 UTC, gorozco1 commented on kernel/update_kernel.sh
> +        if ! curl --fail -O ${KSOURCE}
Please remove the conditional for "file" and always try the download of the kernel with the continue flag.


`curl -L -O -C - "${KSOURCE}"`

2017-08-23 22:31 UTC, miguelinux commented
@gorozco1 the change is done, Could you review? please.

2017-08-23 23:06 UTC, MarioCarrilloA commented on kernel/update_kernel.sh
> +for i in `cat obs_working_dir/debian/patches/series`
Maybe you could use $() instead of ``

2017-08-23 23:07 UTC, MarioCarrilloA commented
@miguelinux could you please update README file too :)

2017-08-28 17:59 UTC, miguelinux commented
@gorozco1, @MarioCarrilloA changes done

2017-08-28 21:50 UTC, gorozco1 approved these changes

2017-08-28 21:51 UTC, merged